#!/bin/sh /etc/rc.common

START=99
STOP=99

USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /bin/true
    procd_close_instance
}

reload_service() {
    uci commit custom-dhcp
    /etc/init.d/dnsmasq reload
}
